CREATE DATABASE db
USE db
CREATE TABLE User_ (
	UerId NVARCHAR(100) PRIMARY KEY,
	Name VARCHAR(50),
	Email VARCHAR(50),
	Password NVARCHAR(50),
	Avatar IMAGE
)

CREATE TABLE Post (
	PostId NVARCHAR(100) PRIMARY KEY,
	UserId NVARCHAR(100) FOREIGN KEY REFERENCES User_(UerId),
	Title VARCHAR(50),
	Short_Info VARCHAR(50),
	Details NVARCHAR(MAX),
	Likes INT
)

CREATE TABLE Post_Liked(
	Post NVARCHAR(100) FOREIGN KEY REFERENCES Post(PostId),
	UserId NVARCHAR(100) FOREIGN KEY REFERENCES User_(UerId)
)